name: Laravel Deployment Pipeline

on:
  workflow_dispatch:  # Safe for manual testing
  push:
    branches:
      - main           # Will deploy only when merged to main

jobs:
  deploy:
    name: Laravel Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to EC2 instance"
            bash /home/ubuntu/github_actions_script/deploy.sh



